routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductoController;
use App\Http\Controllers\RestauranteController;
use App\Http\Controllers\RestauranteProductoController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name("inicio");

Route::get('/proyecto', function () {
    return view('proyecto.index');
})->name("index");

Route::get('/restaurantes', function () {
    return view('index');
})->name("listaRestaurantes");

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('welcome');
});


Route::resource("restaurantes", RestauranteController::class)->middleware('auth');
Route::resource("producto", ProductoController::class);

Route::get('/allRestaurantes', [RestauranteController::class, 'allRestaurantes'])->name('restaurante.allRestaurantes');

Route::get('/listaProductos/{restaurante}', [RestauranteController::class, 'listaProductos'])->name('restaurante.listaProductos');

// Route::delete('/deleteRP/{restaurante}/{producto}', [RestauranteProductoController::class, 'deleteRP'])->name('restauranteProducto.deleteRP');
// Route::get('/añadirProductoRestaurante/{restaurante}', [RestauranteProductoController::class, 'añadirProductoRestaurante'])->name('restauranteProducto.añadirProductoRestaurante');
// Route::post("/storeProducto/{restaurante}", [RestauranteProductoController::class, 'storeProducto'])->name("restauranteProducto.storeProducto")->middleware('auth');

resources/views/proyecto/_formAñadirProducto.blade.php
@extends ('plantillas.master')

@section('title')
Añadir producto
@stop


@section('central')
<h2>Añadir producto:</h2>

<form action="{{ route('restauranteProducto.storeProducto', $restaurante->id) }}" method="post">

    <div class="mb-3">

        <h5 for="titulo" class="form-label">{{$restaurante->nombre}}</h5><br>

        <label for="titulo" class="form-label">Productos:</label>

        <select name="producto_id" class="form-control" id="$producto_id">
            <option value="0">Seleccione un producto</option>
            @foreach ($listaProductos as $producto)
            <option value="{{ $producto->id }}">{{ $producto->nombre}}</option>
            @endforeach
        </select>
        @error('titulo')
        <small class='alert alert-danger'>{{ $message }}</small>
        @enderror

    </div>
    @csrf
    <input type="submit" class="btn btn-success" value="Añadir" />

</form>

@stop

resources/views/proyecto/_formProducto.blade.php
@csrf
<div class="mb-3">
    <label for="nombre" class="form-label">Nombre:</label>
    <input type="text" class="form-control" id="nombre" name="nombre" value="{{ old('nombre',$producto->nombre) }}" maxlength="50">
    @error('nombre')
    <small class='alert alert-danger'>{{ $message }}</small>
    @enderror
</div>


<div class="mb-3">
    <label for="descripcion" class="form-label">Descripcion:</label>
    <input type="text" class="form-control" id="descripcion" name="descripcion" value="{{ old('descripcion',$producto->descripcion) }}" maxlength="200">
    @error('descripcion')
    <small class='alert alert-danger'>{{ $message }}</small>
    @enderror
</div>

<div class="mb-3">
    <label for="precio" class="form-label">Precio:</label>
    <input type="number" class="form-control" id="precio" name="precio" value="{{ old('precio',$producto->precio) }}" maxlength="10">
    @error('precio')
    <small class='alert alert-danger'>{{ $message }}</small>
    @enderror
</div>

<div class="mb-3">
    <label for="foto" class="form-label">Fotografía producto :</label> <strong>{{ old('foto',$producto->foto) }}</strong>
    <input type="file" class="form-control" id="foto" name="foto" value="{{ old('foto',$producto->foto) }}" maxlength="100">
    @if ($errors->has('foto'))
    <small class='alert alert-danger'>{{ $errors->first('foto') }}</small>
    @endif
</div>

resources/views/proyecto/_formRestaurante.blade.php
@csrf

 <div class="row p-2">

    <div class="col-md-1 offset-md-2">
        <span class="text-center text-light"><i class="fa-solid fa-house-chimney fa-2x"></i></span>
    </div>
    <div class="col-md-7 ">
        <input type="text" class="form-control" id="nombre" placeholder="Nombre"  name="nombre" value="{{ old('nombre',$restaurante->nombre) }}" maxlength="50">
        @error('nombre')
        <small class='alert alert-danger'>{{ $message }}</small>
        @enderror   
    </div>
    
</div>

<div class="row p-2">
   
    <div class="col-md-1 offset-md-2">
        <span class="text-center text-light"><i class="fa-solid fa-phone fa-2x"></i></i></span>
    </div>
    <div class="col-md-7 ">
        <input type="text" class="form-control" id="telefono" placeholder="Télefono" name="telefono" value="{{ old('telefono',$restaurante->telefono) }}" maxlength="200">
        @error('telefono')
        <small class='alert alert-danger'>{{ $message }}</small>
        @enderror  
    </div>

</div>

<div class="row p-2">

    <div class="col-md-1 offset-md-2">
        <span class="text-center text-light"><i class="fa-solid fa-map-location fa-2x"></i></i></span>
    </div>
    <div class="col-md-7 ">
        <input type="text" class="form-control" id="direccion" placeholder="Dirección" name="direccion" value="{{ old('direccion',$restaurante->direccion) }}" maxlength="200">
        @error('direccion')
        <small class='alert alert-danger'>{{ $message }}</small>
        @enderror  
    </div>

</div>


<div class="row p-2">

    <div class="col-md-1 offset-md-2">
        <span class="text-center text-light"><i class="fa-solid fa-image fa-2x"></i></span>
    </div>
    <div class="col-md-7 ">
        <input type="file" class="form-control" id="foto" name="foto" value="{{ old('foto',$restaurante->foto) }}" maxlength="100">
        @if ($errors->has('foto'))
        <small class='alert alert-danger'>{{ $errors->first('foto') }}</small>
        @endif
    </div>

</div>
        

resources/views/proyecto/createProducto.blade.php
@extends ('plantillas.master')

@section('title')
Crear producto
@stop


@section('central')

<h2>Crear producto</h2>

<form class="m-5 bg-white rounded" action="{{ route('producto.store') }}" method="post" enctype="multipart/form-data">

    <div class="container">
        
            @include ('proyecto._formProducto')
        
    </div>

    <input type="reset" class="btn btn-danger" value="Limpiar" />
    <input type="submit" class="btn btn-success" value="Crear" />
</form>

@stop

resources/views/proyecto/createRestaurante.blade.php
@extends ('plantillas.master')

@section('title')
Crear restaurante
@stop

@section('central')


    <h2 class=" p-4 bg-white rounded-pill"><center>Crear restaurante</center></h2>

    <div class="p-4">
        <div class=" bg-info rounded-pill p-4">
            
            <form action="{{ route('restaurantes.store') }}" method="post" enctype="multipart/form-data">

                @include ('proyecto._formRestaurante')

                <div class="d-flex justify-content-center align-item-center">
                    <input type="reset" class="btn btn-danger text-white m-2" value="LIMPIAR" />
                    <input type="submit" class="btn btn-success text-white m-2" value="CREAR" />
                </div>
            </form>
        </div>
    </div>
@stop

resources/views/proyecto/editRestaurante.blade.php
@extends ('plantillas.master')

@section('title')
Editar restaurante
@stop


@section('central')
    <h2 class=" p-4 bg-white rounded-pill"><center>Editar restaurante</center></h2>

    <div class="p-4">
        <div class=" bg-info rounded-pill p-4">

    <form action="{{ route('restaurantes.update', $restaurante) }}" method="post" enctype="multipart/form-data">
        @method('PUT')
        @include ('proyecto._formRestaurante')

        <div class="d-flex justify-content-center align-item-center">
            <input type="reset" class="btn btn-danger text-white m-2" value="LIMPIAR" />
            <input type="submit" class="btn btn-success text-white m-2" value="EDITAR" />
        </div>
    </form>

@stop

resources/views/proyecto/editarProducto.blade.php
@extends ('plantillas.master')

@section('title')
Editar producto
@stop


@section('central')
<h2>Editar producto</h2>

<form action="{{ route('producto.update', $producto->id) }}" method="post" enctype="multipart/form-data">
    @method('PUT')
    @include ('proyecto._formProducto')

    <input type="reset" class="btn btn-danger" value="Limpiar" />
    <input type="submit" class="btn btn-success" value="Editar" />
</form>

@stop

resources/views/proyecto/index.blade.php
@extends ('plantillas.master')

@section('title')
Listado de eventos
@stop

@section('central')

<div class="p-5">


    <h2 class="p-4 bg-white rounded-pill"><center>LISTADO DE RESTAURANTES <a id="btnCreate" href="{{ route('restaurantes.create')}}"><i class="fa-solid fa-circle-plus "></i></a></center></h2>

    @if(Session::has("mensaje"))
    <div class="alert {{ Session::get('alert-class') }}">
        {{Session:get('mensaje')}}
    </div>
    @endif

    
    <div class="container">
        <div class="row">
            

        @foreach ($restaurantes as $restaurante)

        <p>{{URL::asset("fotos/$restaurante->foto")}}</p>
            <div class="col col-xl-4 col-md-6 d-flex justify-content-center align-items-center p-3">
                <div class="card border-dark text-center shadow p-3" style="width: 20rem;border: 3px solid rgb(236, 142, 60)">
                    
                    @if(isset($restaurante->foto) && $restaurante->foto!="foto.png") 
                        <img class="card-img-top rounded-circle" style="border: 5px solid rgb(89, 87, 87)" width="200" height="300" src='{{URL::asset("fotos/$restaurante->foto")}}'>  
                    @else
                        <img class="card-img-top rounded-circle opacity-25"  src='{{URL::asset("img/interrogacion.png")}}' alt="Card image cap">
                    @endif 

                    <div class="card-body  ">
                        <h5 class="card-title p-2 text-white" style="background-color: rgb(196, 190, 188);border-radius:10px">{{$restaurante->nombre}}</h5>
                        <p class="card-text">{{$restaurante->direccion}}</p>
                        
                        <div class="d-flex justify-content-center  justify-content-between">

                            {{-- VER MAS --}}
                            <form action="{{route('restaurante.listaProductos',$restaurante)}}" method="get" enctype='multipart/form-data'>
                                <button type="submit" class="btn btn-primary text-white">
                                    <i class="fa-solid fa-bars"></i>
                                </button>
                            </form>
                            {{-- EDITAR --}}
                            <form action="{{ route('restaurantes.edit', $restaurante) }}" method="get">
                                @csrf
                                @method('PUT')
                                <button type="submit" class="btn btn-warning text-dark">
                                    <i class="fa-solid fa-pen-to-square "></i>
                                </button>
                            </form>

                            {{-- BORRAR --}}
                            <form action="{{ route('restaurantes.destroy', ['restaurante'=>$restaurante->id]) }}" method="post">
                                @csrf
                                @method(' DELETE')
                                <button type="submit" class="btn btn-danger text-white">
                                    <i class="fa-solid fa-trash-can"></i>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            
        @endforeach
        </div>
        <div class="row">
            <div class="d-flex justify-content-center">
                <p>{!! $restaurantes->links() !!}</p>
            </div>
        </div>
    </div>

</div>
@stop

resources/views/proyecto/listarProductos.blade.php
@extends ('plantillas.master')

@section('title')
Listado de productos
@stop


@section('central')
<div class="p-5">
    <h2><center>Listado de Productos
        @if(Auth::user()->admin)
            <a href="{{ route('restauranteProducto.añadirProductoRestaurante',$restaurante)}}" class="btn btn-success text-white rounded-circle" title="Añadir Producto">+</a>
        @endif
    </center></h2>

    @if(Session::has("mensaje"))
    <div class="alert {{ Session::get('alert-class') }}">
        {{Session:get('mensaje')}}
    </div>
    @endif


    {{-- <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre</th>
                <th scope="col">Descripcion</th>
                <th scope="col">Precio</th>
                <th scope="col">Foto</th>
            </tr>
        </thead>
        <tbody>

            <p>Restaurante -> {{$restaurante->id}}</p>

            @foreach ($listproductos as $producto)
            <tr>
                <th scope="row">{{$producto->id}}</th>
                <td>{{$producto->nombre}}</td>
                <td>{{$producto->descripcion}}</td>
                <td>{{$producto->precio}}</td>
                @if( $producto->foto != "Foto.png")
                <td><img width="200" src='{{ URL::asset("storage/$producto->foto") }}'></td>
                @else
                <td>{{$producto->foto}}</td>
                @endif

                <td>
                    @if(Auth::user()->admin)
                    <form action="{{ route('restauranteProducto.deleteRP', ['restaurante'=>$restaurante->id, 'producto'=>$producto]) }}" method="post">
                        @csrf
                        @method(' DELETE')
                        <input type="submit" class="btn btn-danger text-white" value="Eliminar">
                    </form>
                    <a href="{{ route('producto.edit', $producto) }}" class="btn btn-warning">Modificar</a>
                    @endif
                </td>
            </tr>
            @endforeach


        </tbody>
    </table> --}}
</div>



<div class="container ">
    <div class="col-10 offset-1 ">
        <div class="row">
            
            <div class="col-md-12">
                <div class=" table-responsive mb-0 bg-white p-4 shadow-sm">
                    <table class="table manage-candidates-top mb-0">

                        <thead>
                            <tr>
                                <th class="text-center">Información</th>
                                <th class="text-center">Opinión</th>
                                <th class="action text-right">Precio</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach ($listproductos as $producto)
                                <tr class="candidates-list">

                                    <td class="title">
                                        <div class="container">
                                            <div class="row">
                                                <div class="col-4">
                                                    <img class="img-fluid" width="80" height="80" src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="">
                                                </div>
                                                <div class="col-8">
                                                    <div class="row p-3">
                                                        <div class="col">
                                                            <h5 ><a href="#">{{$producto->nombre}}</a></h5>
                                                        </div>
                                                        <div class="col">
                                                            {{$producto->precio}}<i class="fa-solid fa-euro-sign"></i>
                                                        </div>
                                                    </div>
                                                    <div>
                                                        <div class="row">
                                                            <div class="col">
                                                                <i class="fa-light fa-file-lines"></i>{{$producto->descripcion}}
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </td>

                                    <td class=" text-center">
                                        
                                        <ul class="list-unstyled ">
                                            <li class="p-2">
                                                <i  class="fa-regular fa-thumbs-up"></i><span id='pulgarUp_{{$producto->id}}' class=" order-1"> 0</span>
                                            </li>
                                            <li class="p-2">
                                                <i  class="fa-regular fa-thumbs-down"></i><span id='pulgarDown_{{$producto->id}}' class=" order-1"> 0</span>
                                            </li>                                            

                                        </ul>
                                        
                                    </td>

                                    <td>
                                        <ul class="list-unstyled ">
                                            <li><a href="#" class="text-primary text-center" data-toggle="tooltip" title="" data-original-title="view"><i class="far fa-eye"></i></a></li>
                                            <li><a href="#" class="text-warning text-center" data-toggle="tooltip" title="" data-original-title="Edit"><i class="fas fa-pencil-alt"></i></a></li>
                                            <li><a href="#" class="text-danger text-center" data-toggle="tooltip" title="" data-original-title="Delete"><i class="far fa-trash-alt"></i></a></li>
                                        </ul>
                                    </td>

                                </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
</div>